In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/TensorFlow/Github

/content/drive/MyDrive/TensorFlow/Github


In [3]:
username = 'Milan-Chicago'
git_token = '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'
repository = 'TensorFlow'

In [4]:
!git clone https://{git_token}@github.com/{username}/{repository}



fatal: destination path 'TensorFlow' already exists and is not an empty directory.


In [5]:
%cd {repository}

/content/drive/MyDrive/TensorFlow/Github/TensorFlow


In [6]:
%ls -a

.git/


In [7]:
!git commit -m "Testing setting up colab to github"


*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@43b41eaa657f.(none)')


In [8]:
!git config --global user.email "mcgraw@uchicago.edu"

In [9]:
!git status

On branch master

No commits yet

nothing to commit (create/copy files and use "git add" to track)


## Set up TensorFlow

Import TensorFlow into your program to get started:

In [15]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


If you are following along in your own development environment, rather than [Colab](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb), see the [install guide](https://www.tensorflow.org/install) for setting up TensorFlow for development.

Note: Make sure you have upgraded to the latest `pip` to install the TensorFlow 2 package if you are using your own development environment. See the [install guide](https://www.tensorflow.org/install) for details.

## Load a dataset

Load and prepare the [MNIST dataset](http://yann.lecun.com/exdb/mnist/). Convert the sample data from integers to floating-point numbers:

In [16]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


## Build a machine learning model

Build a `tf.keras.Sequential` model by stacking layers.

In [17]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

For each example, the model returns a vector of [logits](https://developers.google.com/machine-learning/glossary#logits) or [log-odds](https://developers.google.com/machine-learning/glossary#log-odds) scores, one for each class.

> Indented block

> Indented block

In [18]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.3136265 , -0.12070347, -0.43459448, -0.30022198,  0.24291186,
         0.9614334 , -0.39752695, -0.08065964,  0.5431596 , -0.4562915 ]],
      dtype=float32)

The `tf.nn.softmax` function converts these logits to *probabilities* for each class: 

In [19]:
tf.nn.softmax(predictions).numpy()

array([[0.06738376, 0.08172231, 0.05970621, 0.06829309, 0.11755925,
        0.24116081, 0.06196091, 0.0850612 , 0.15872769, 0.05842472]],
      dtype=float32)

Note: It is possible to bake the `tf.nn.softmax` function into the activation function for the last layer of the network. While this can make the model output more directly interpretable, this approach is discouraged as it's impossible to provide an exact and numerically stable loss calculation for all models when using a softmax output. 

In [22]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

Define a loss function for training using `losses.SparseCategoricalCrossentropy`, which takes a vector of logits and a `True` index and returns a scalar loss for each example.

This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to `-tf.math.log(1/10) ~= 2.3`.

In [23]:
loss_fn(y_train[:1], predictions).numpy()

1.4222913

In [25]:
# This is formatted as code


Before you start training, configure and compile the model using Keras `Model.compile`. Set the [`optimizer`](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers) class to `adam`, set the `loss` to the `loss_fn` function you defined earlier, and specify a metric to be evaluated for the model by setting the `metrics` parameter to `accuracy`.

In [27]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

## Train and evaluate your model

Use the `Model.fit` method to adjust your model parameters and minimize the loss:

In [28]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2932 - accuracy: 0.9147
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1439 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1081 - accuracy: 0.9664
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0873 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0740 - accuracy: 0.9765


The `Model.evaluate` method checks the models performance, usually on a "[Validation-set](https://developers.google.com/machine-learning/glossary#validation-set)" or "[Test-set](https://developers.google.com/machine-learning/glossary#test-set)".


In [30]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0811 - accuracy: 0.9744 - 790ms/epoch - 3ms/step


[0.08108988404273987, 0.974399983882904]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the [TensorFlow tutorials](https://www.tensorflow.org/tutorials/).

*If* you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [31]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [32]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.50917623e-07, 6.91490598e-08, 1.01335092e-04, 4.83920798e-03,
        1.74148994e-11, 7.52610777e-06, 1.21031180e-11, 9.95022774e-01,
        9.56817712e-06, 1.93560099e-05],
       [1.85534299e-09, 4.74135159e-05, 9.99936819e-01, 4.97508381e-06,
        1.47643031e-15, 1.01395635e-05, 7.23443918e-08, 4.07965033e-15,
        5.26291785e-07, 3.60905357e-14],
       [2.64406399e-08, 9.99533415e-01, 3.20346262e-05, 4.06258187e-06,
        6.51831624e-06, 3.90463765e-06, 4.04875846e-06, 3.55068274e-04,
        6.07423572e-05, 1.20215901e-07],
       [9.99753177e-01, 3.43683437e-09, 2.80849181e-05, 3.96544783e-06,
        5.52503963e-08, 3.27362613e-05, 6.14310920e-05, 3.57226418e-05,
        3.99763707e-07, 8.44381211e-05],
       [4.28287494e-05, 2.53840993e-09, 2.75434613e-05, 1.08471750e-06,
        9.89603102e-01, 3.56884948e-06, 4.13495654e-05, 2.77451065e-04,
        1.64029279e-06, 1.00014396e-02]], dtype=float32)>

**bold text**## Conclusion

Congratulations! You have trained a machine learning model using a prebuilt dataset using the [Keras](https://www.tensorflow.org/guide/keras/overview) API.

For more examples of using Keras, check out the [tutorials](https://www.tensorflow.org/tutorials/keras/). To learn more about building models with Keras, read the [guides](https://www.tensorflow.org/guide/keras). If you want learn more about loading and preparing data, see the tutorials on [image data loading](https://www.tensorflow.org/tutorials/load_data/images) or [CSV data loading](https://www.tensorflow.org/tutorials/load_data/csv).


In [37]:
# Once you are satisfied with your work and want to save your commits to GitHub, you can simply push your commits to GitHub using git push command.
!git add .

In [34]:
!git commit -m "Udating this workbook"

On branch master

Initial commit

nothing to commit


In [38]:
!git push


error: src refspec refs/heads/master does not match any.
error: failed to push some refs to 'https://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@github.com/Milan-Chicago/TensorFlow'
